"""nice_things_django_project URL Configuration

DIRECT COPY (originally generated by Django, modified by authors)

Authors: Tyler Amos, Alexander Tyan
"""

from django.urls import include, path
from django.contrib import admin

# adapted from pa3
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itinerary.urls'))
]
