"""
DIRECT COPY (originally generated by Django)

Authors: Tyler Amos, Kevin Sun, Alexander Tyan
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "nice_things_django_project.settings")

application = get_wsgi_application()
